name: greenrail
description: "GreenRail is a RedRail clone."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1
  go_router: ^14.1.4
  google_fonts: ^6.2.1
  intl: ^0.19.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.3.5

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.3
  isar_generator: ^3.1.0+1
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.2

flutter:
  uses-material-design: true
